[2024-04-18T02:05:22.047+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-18T02:05:22.059+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sagemaker_workflow.train_model manual__2024-04-18T02:05:15.431014+00:00 [queued]>
[2024-04-18T02:05:22.065+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sagemaker_workflow.train_model manual__2024-04-18T02:05:15.431014+00:00 [queued]>
[2024-04-18T02:05:22.065+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-18T02:05:22.079+0000] {taskinstance.py:2327} INFO - Executing <Task(SageMakerTrainingOperator): train_model> on 2024-04-18 02:05:15.431014+00:00
[2024-04-18T02:05:22.083+0000] {standard_task_runner.py:63} INFO - Started process 2870 to run task
[2024-04-18T02:05:22.086+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'sagemaker_workflow', 'train_model', 'manual__2024-04-18T02:05:15.431014+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/SageMaker-Workflow-dag2.py', '--cfg-path', '/tmp/tmp3xg6tbc_']
[2024-04-18T02:05:22.086+0000] {standard_task_runner.py:91} INFO - Job 25: Subtask train_model
[2024-04-18T02:05:22.121+0000] {task_command.py:426} INFO - Running <TaskInstance: sagemaker_workflow.train_model manual__2024-04-18T02:05:15.431014+00:00 [running]> on host ip-172-31-82-179.ec2.internal
[2024-04-18T02:05:22.285+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='sagemaker_workflow' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-04-18T02:05:15.431014+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-18T02:05:15.431014+00:00'
[2024-04-18T02:05:22.286+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-18T02:05:22.286+0000] {sagemaker.py:110} INFO - Preprocessing the config and doing required s3_operations
[2024-04-18T02:05:22.286+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-18T02:05:22.287+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sagemaker.py", line 1066, in execute
    self.preprocess_config()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/airflow/providers/amazon/aws/operators/sagemaker.py", line 111, in preprocess_config
    self.hook.configure_s3_resources(self.config)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/airflow/providers/amazon/aws/hooks/sagemaker.py", line 182, in configure_s3_resources
    s3_operations = config.pop("S3Operations", None)
AttributeError: 'str' object has no attribute 'pop'
[2024-04-18T02:05:22.296+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=sagemaker_workflow, task_id=train_model, execution_date=20240418T020515, start_date=20240418T020522, end_date=20240418T020522
[2024-04-18T02:05:22.307+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 25 for task train_model ('str' object has no attribute 'pop'; 2870)
[2024-04-18T02:05:22.338+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-18T02:05:22.357+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-18T02:05:22.358+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
