[2024-04-17T12:44:41.793+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: example_display_name.sample_task_2 manual__2024-04-17T12:44:32.493112+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
